[profile.default]
solc_version = '0.8.11'
auto_detect_solc = false
optimizer = true
optimizer_runs = 1_000
fuzz_runs = 1_000
remappings = [
    "forge-std=lib/forge-std/src/",
    "solmate=lib/solmate/src/",
    "solenv=lib/solenv/src/",
    "openzeppelin=lib/openzeppelin-contracts/contracts/",
    "v3-periphery=lib/v3-periphery/contracts/"
]
